# Generated by Django 4.2.7 on 2023-12-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="student",
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
